 USE [master]
GO
/****** Object:  Database [ProjectDatabase]    Script Date: 2023-01-24 15:51:40 ******/
CREATE DATABASE [ProjectDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjectDatabase', FILENAME = N'C:\Users\Lawe Zangena\ProjectDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProjectDatabase_log', FILENAME = N'C:\Users\Lawe Zangena\ProjectDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ProjectDatabase] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjectDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ProjectDatabase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ProjectDatabase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ProjectDatabase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ProjectDatabase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ProjectDatabase] SET ARITHABORT OFF 
GO
ALTER DATABASE [ProjectDatabase] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ProjectDatabase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ProjectDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ProjectDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ProjectDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ProjectDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ProjectDatabase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ProjectDatabase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ProjectDatabase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ProjectDatabase] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ProjectDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ProjectDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ProjectDatabase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ProjectDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ProjectDatabase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ProjectDatabase] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [ProjectDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ProjectDatabase] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ProjectDatabase] SET  MULTI_USER 
GO
ALTER DATABASE [ProjectDatabase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ProjectDatabase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ProjectDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ProjectDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ProjectDatabase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ProjectDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ProjectDatabase] SET QUERY_STORE = OFF
GO
USE [ProjectDatabase]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 2023-01-24 15:51:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CalculationResults]    Script Date: 2023-01-24 15:51:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CalculationResults](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[A] [int] NOT NULL,
	[B] [int] NOT NULL,
	[CreateDate] [datetime2](7) NOT NULL,
	[Operatore] [nvarchar](max) NOT NULL,
	[Sum] [float] NOT NULL,
 CONSTRAINT [PK_CalculationResults] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Results]    Script Date: 2023-01-24 15:51:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Results](
	[Result] [nvarchar](1) NOT NULL,
	[WinRate] [float] NOT NULL,
	[ComputerChoise] [nvarchar](max) NOT NULL,
	[HumanChoise] [nvarchar](max) NOT NULL,
	[GameDate] [datetime2](7) NOT NULL,
	[Id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_Results] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Shapes]    Script Date: 2023-01-24 15:51:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Shapes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Area] [float] NOT NULL,
	[Circumference] [float] NOT NULL,
	[CreateDate] [datetime2](7) NOT NULL,
	[Form] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Shapes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CalculationResults] ADD  DEFAULT ((0.0000000000000000e+000)) FOR [Sum]
GO
ALTER TABLE [dbo].[Shapes] ADD  DEFAULT ((0.0000000000000000e+000)) FOR [Area]
GO
ALTER TABLE [dbo].[Shapes] ADD  DEFAULT ((0.0000000000000000e+000)) FOR [Circumference]
GO
ALTER TABLE [dbo].[Shapes] ADD  DEFAULT ('0001-01-01T00:00:00.0000000') FOR [CreateDate]
GO
ALTER TABLE [dbo].[Shapes] ADD  DEFAULT (N'') FOR [Form]
GO
USE [master]
GO
ALTER DATABASE [ProjectDatabase] SET  READ_WRITE 
GO
